name: Update Libs

on:
  schedule:
    - cron: '43 2 * * *'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update.yaml'
      - 'build/**'
      - 'config/**'
  pull_request:
    paths:
      - '.github/workflows/update.yaml'
      - 'build/**'
      - 'config/**'

jobs:
  AutoLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, push refs to dest repo will fail

      - name: Do Build
        run: |-
          ./build/mage.sh sysdeps wrap archive
          mv /tmp/go-libtor.tar /tmp/go-libtor-linux.tar

      - uses: actions/upload-artifact@v2
        with:
          name: go-libtor-linux
          path: /tmp/go-libtor-linux.tar
          if-no-files-found: error

  AutoDarwin:
    runs-on: macos-latest
    needs: AutoLinux
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, push refs to dest repo will fail

      - name: Do Build
        run: |-
          ./build/mage.sh sysdeps wrap archive
          mv /tmp/go-libtor.tar /tmp/go-libtor-darwin.tar

      - uses: actions/upload-artifact@v2
        with:
          name: go-libtor-darwin
          path: /tmp/go-libtor-darwin.tar
          if-no-files-found: error

  TestLinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openssl: [ "dyn", "sta" ]
        libevent: [ "dyn", "sta" ]
        zlib: [ "dyn", "sta" ]
    needs: AutoLinux
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Download the last build
        uses: actions/download-artifact@v2
        with:
          name: go-libtor-linux
          path: .

      - name: Building
        env:
          OPENSSL_TYPE: ${{ matrix.openssl }}
          LIBEVENT_TYPE: ${{ matrix.libevent }}
          ZLIB_TYPE: ${{ matrix.zlib }}
        run: |
          ./build/mage.sh testBuildMatrix "$ZLIB_TYPE" "$OPENSSL_TYPE" "$LIBEVENT_TYPE"

  TestMacosDynamic:
    runs-on: macos-latest
    needs: AutoDarwin
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Download the last build
        uses: actions/download-artifact@v2
        with:
          name: go-libtor-darwin
          path: .

      - name: Building
        run: |
          ./build/mage.sh testBuildDynamic

  TestMacosStatic:
    runs-on: macos-latest
    needs: AutoDarwin
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Download the last build
        uses: actions/download-artifact@v2
        with:
          name: go-libtor-darwin
          path: .

      - name: Building
        run: |
          ./build/mage.sh testBuildDynamic

# TestIOS:
#   runs-on: macos-latest
#   needs: AutoDarwin
#   steps:
#     - name: Set up Go 1.x
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.15.3
#
#     - name: Download the last build
#       uses: actions/download-artifact@v2
#       with:
#         name: go-libtor-darwin
#         path: .
#
#     - name: Building
#       run: |
#         go get -u golang.org/x/mobile/cmd/gomobile
#         gomobile init
#         tar xf go-libtor.tar
#         cd go-libtor
#         gomobile bind -target=ios -tags="staticOpenssl staticZlib staticLibevent" .

#  Push:
#    runs-on: ubuntu-latest
#    needs: [ TestLinux, TestMacosDynamic, TestMacosStatic, TestIOS ]
#    if: github.ref == 'refs/heads/master'
#    env:
#      ED25519_KEY: ${{secrets.ED25519_KEY}}
#    steps:
#      - name: Download the last build
#        uses: actions/download-artifact@v2
#        with:
#          name: go-libtor-darwin
#          path: .
#
#      - name: Run Script
#        run: |
#          tar xf go-libtor.tar
#          cd go-libtor
#          build/push.sh
